-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.12.0.240.2
-- Module  Version: 5.7
-- Sat Dec 04 17:09:40 2021

-- parameterized module component declaration
component pll
    port (CLK: in std_logic; RESET: in std_logic; CLKOP: out std_logic; 
        CLKOK: out std_logic; LOCK: out std_logic);
end component;

-- parameterized module component instance
__ : pll
    port map (CLK=>__, RESET=>__, CLKOP=>__, CLKOK=>__, LOCK=>__);
