-- VHDL module instantiation generated by SCUBA ispLever_v70_SP1_Build (25)
-- Module  Version: 3.1
-- Mon Feb 18 21:57:32 2008

-- parameterized module component declaration
component clut
    port (WrAddress: in  std_logic_vector(3 downto 0); 
        Data: in  std_logic_vector(8 downto 0); WrClock: in  std_logic; 
        WE: in  std_logic; WrClockEn: in  std_logic; 
        RdAddress: in  std_logic_vector(3 downto 0); 
        Q: out  std_logic_vector(8 downto 0));
end component;

-- parameterized module component instance
__ : clut
    port map (WrAddress(3 downto 0)=>__, Data(8 downto 0)=>__, WrClock=>__, 
        WE=>__, WrClockEn=>__, RdAddress(3 downto 0)=>__, Q(8 downto 0)=>__);
