-- VHDL module instantiation generated by SCUBA ispLever_v70_SP1_Build (25)
-- Module  Version: 3.6
-- Sun Oct 05 18:15:09 2008

-- parameterized module component declaration
component pll
    port (CLK: in std_logic; RESET: in std_logic; CLKOP: out std_logic; 
        CLKOS: out std_logic; CLKOK: out std_logic; LOCK: out std_logic);
end component;

-- parameterized module component instance
__ : pll
    port map (CLK=>__, RESET=>__, CLKOP=>__, CLKOS=>__, CLKOK=>__, LOCK=>__);
