#ifndef _WEBSIDE_INCLUDED_
#define _WEBSIDE_INCLUDED_
#include <ctype.h>
#include <stdlib.h>
//#include "dynhtml.h"
#define	INFO_VERSION	"Software-Version 1.0"

const char NameOfWebSide[]="index.htm";
extern char *pCnt;

//tDynHtml code dynWebSide[]= {{"cnt",pCnt},
//							 {0,0}};

const unsigned char WebSide[] = {
"<html>\r\n"
"<head>\r\n"
"<title>Sandbox "__DATE__"/"__TIME__" "INFO_VERSION"</title>\r\n"
"</head>\r\n"
"<body bgcolor=\"#3366ff\" text=\"#ffffff\" link=\"#79fbfb\" vlink=\"#79fbfb\" alink=\"#79fbfb\">\r\n"
//"<i><img src=\"hsse.jpg\" align=\"left\" width=\"100\" height=\"108\"></i>\r\n"
"<i><img src=\"fh.gif\" width=\"194\" height=\"86\" align=\"left\"><img src=\"hsse.jpg\" align=\"right\" width=108 height=108></i><br><br><br><br><br><br><br>\r\n"
"<table width=700 border=0><tr><td>\r\n"
"<b><font color=\"#ffcc00\" size=\"6\"><i>Embedded Webserver Modul</i></font></b></td>\r\n"
"<td align=right><b><font size=-1>Internet: <a href=\"http://www.fhs-hagenberg.ac.at/\">http://www.fhs-hagenberg.ac.at</a></b></font></td>\r\n"
"<tr><td><b><font color=\"#000000\" size=\"3\"><i>Sandbox with ATmega128</i></font></b></td>\r\n"
"<td align=right><b><font size=-1>E-Mail: <a href=\"mailto:hse00045@fhs-hagenberg.ac.at?subject=Sandbox Webserver\">hse00045@fhs-hagenberg.ac.at</a></font></b>\r\n"
"</td></tr></table>\r\n"
"<table width=900 border=0>\r\n"
"<tr>\r\n"
"<tr><B>@cnt@</B> Zugriffe seit Powerup\r\n"
"<td colspan=3 valign=top><br>The Sandbox Embedded Webserver - a powerful solution with 80C517A<sup>TM</sup> and CS8900 Ethernet Controller ("
INFO_VERSION" of "__DATE__"/"__TIME__")<br><br></td></tr>\r\n"
"<tr><td width=340 valign=top>\r\n"
"<b>Board Features</b><br><br>\r\n"
"<ul><li>68000 Microcontroller</li>\r\n"
"<li>10 Mbit Ethernetcontroller CS8900</li>\r\n"
"<li>10 MHz</li>\r\n"
"<li>1024k ROM</li>\r\n"
"<li>64k RAM</li>\r\n"
"<li>512x256 Grafik</li>\r\n"
"<li>ATmega128 Microcontroller</li>\r\n"
"<li>100 Mbit Ethernetcontroller W3100</li>\r\n"
"<li>Spartan II FPGA</li>\r\n"
"<li>Flash PROM</li>\r\n"
"<li>Zwei gemultiplexte 7-Segment Anzeigen</li>\r\n"
"<li>Serielle Schnittstelle</li>\r\n"
"<li>Tastenfeld mit 12 Tastern</li>\r\n"
"<li>12 beliebig ansteuerbare LEDs</li>\r\n"
"<li>24-Bit Audiocodec</li>\r\n"
"<li>VGA Ausgang</li>\r\n"
"<li>Single Step Clock</li>\r\n"
"<li>Infrarot Schnittstelle</li>\r\n"
"<li>PS2 Mouse und Tastaturanschluss</li>\r\n"
"<li>Midi Interface</li>\r\n"
"<li>TOSLINK Interface</li>\r\n"
"<li>Mehrere freikonfigurierbare Schnittstellen (VG96,..)</li>\r\n"
"<li>Flash ROM</li>\r\n"
"<li>Atmel AVR MEGA128 Mikrocontroller</li>\r\n"
"<li>RS232 </li>\r\n"
"<li>RS485</li>\r\n"
"<li>I�C Real Time Clock</li>\r\n"
"<li>I�C Bus</li>\r\n"
"<li>SPI Bus</li>\r\n"
"<li>6 Taster</li>\r\n"
"<li>6 LEDs</li>\r\n"
"<li>JTAG Interface</li>\r\n"
"<li>Programmierschnittstelle �ber serielle Schnittstelle (Ponyprog)</li>\r\n"
"<li>Analog Digital Converter Interface</li>\r\n"
"<li>LCD Display</li>\r\n"
"<li>16 Bit externer Daten-/Adressbus</li>\r\n"
"<li>14 Bit breiter Bus zum FPGA mit Interrupteingang</li>\r\n"
"<li>Schnittstelle f�r externe Interrupts und PWM</li>\r\n"


"</td><td width=20>&nbsp;</td><td width=540 valign=top>\r\n"
"<b>Sandbox Ports</b><br><br>\r\n"
"<li>Port A 0�7:	verbunden mit Spartan; Adress-/Datenbus und Buchsenstecker</li>\r\n"
"<li>Port B 0:	SS und Display	</li>\r\n"
"<li>Port B 1..3:	SPI Interface</li>\r\n"
"<li>Port B 4..7 :	Display</li>\r\n"

"<li>Port C 0..7 :	verbunden mit Spartan; Adress-/Datenbus und Buchsenstecker</li>\r\n"

"<li>Port D0..1:	I�C Schnittstelle, wird mit der Uhr verbunden und nach au�en gef�hrt</li>\r\n"
"<li>Port D2..3:	RS232</li>\r\n"
"<li>Port D4..7:	Taster und LEDs</li>\r\n"

"<li>Port E0..1:	RS485 oder Programing Pins (MOSI u. MISO) ->DIP Schalter	, Ponyprog</li>\r\n"
"<li>Port E2, 3:	Sende- und Empfangs Enable f�r RS485</li>\r\n"
"<li>Port E4,5:	Interrupts oder PWM Ausgang, auf Buchsenstecker nach au�en gef�hrt </li>\r\n"
"<li>Port E6:	Externer Interrupt mit LED und Taste, auf Buchsenstecker nach au�en und parallel auf Adress/Datenbus und Interrupteingang f�r den Spartan (mit Jumper einschaltbar)</li>\r\n"
"<li>Port E7:	Externer Interrupt mit LED und Taste, auf Buchsenstecker nach au�en gef�hrt und parallel Interrupt der RTC</li>\r\n"

"<li>Port F0..3 :	�ber Steckerwanne nach au�en, AD-Wandler</li>\r\n"
"<li>Port F4..7:	JTAG Schnittstelle und nach au�en gef�hrt f�r AD-Wandler</li>\r\n"

"<li>Port G.0:	Write, verbunden mit Spartan und Buchsenstecker</li>\r\n"
"<li>Port G.1:	Read, verbunden mit Spartan und Buchsenstecker</li>\r\n"
"<li>Port G.2 :	Adress Latch Enable, verbunden mit Spartan und Buchsenstecker</li>\r\n"
"<li>Port G3..4 :	LCD-Enable und LCD-Read Write Signale</li>\r\n"


"</td></tr></table> <br><br><br><br>"
/*"<b>A/D Converter-Channel 0 :</b><br><br>\r\n"
"<table bgcolor=\"#00ff00\" border=\"5\" cellpadding=\"0\" cellspacing=\"0\" width=\"500\">\r\n"
"<tr>\r\n"
"<td>\r\n"
"<table width=\"AD0%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
"<tr><td bgcolor=\"#ff0000\">&nbsp;</td></tr>\r\n"
"</table>\r\n"
"</td>\r\n"
"</tr>\r\n"
"</table>\r\n"
"<table border=\"0\" width=\"500\">\r\n"
"<tr>\r\n"
"<td width=\"20%\">0V</td>\r\n"
"<td width=\"20%\">0.5V</td>\r\n"
"<td width=\"20%\">1V</td>\r\n"
"<td width=\"20%\">1.5V</td>\r\n"
"<td width=\"20%\">2V</td>\r\n"
"<td width=\"20%\">2.5V</td>\r\n"
"</tr>\r\n"
"</table>\r\n"
"<br><b>A/D Converter-Channel 1 :</b><br><br>\r\n"
"<table bgcolor=\"#00ff00\" border=\"5\" cellpadding=\"0\" cellspacing=\"0\" width=\"500\">\r\n"
"<tr>\r\n"
"<td>\r\n"
"<table width=\"AD1%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
"<tr><td bgcolor=\"#ff0000\">&nbsp;</td></tr>\r\n"
"</table>\r\n"
"</td>\r\n"
"</tr>\r\n"
"</table>\r\n"
"<table border=\"0\" width=\"500\">\r\n"
"<tr>\r\n"
"<td width=\"20%\"> 0V</td>\r\n"
"<td width=\"20%\">0.5V</td>\r\n"
"<td width=\"20%\">1V</td>\r\n"
"<td width=\"20%\">1.5V</td>\r\n"
"<td width=\"20%\">2V</td>\r\n"
"<td width=\"20%\">2.5V</td>\r\n"
"</tr>\r\n"
"</table>\r\n"*/
/*"<form action=\""CGIFORMULAR1"\" method=\"POST\">\r\n"
"<p><strong>Geben Sie Ihren Kommentar in folgendes Feld ein:</strong></p>\r\n"
"<dl>\r\n<dd><textarea name=\"Kommentare\" rows=\"5\" cols=\"42\"></textarea></dd>\r\n"
"</dl>\r\n"
"<p><input type=\"submit\" value=\"abschicken\"> <input type=\"reset\" value=\"Formular zur�cksetzen\"></p>\r\n"
"</form>\r\n" */
"<p>&nbsp;</p>\r\n"
"<p>Hier k�nnen Sie die <a href=\"io.htm\">Sandbox Peripherals</a> ansehen und ver�ndern</p>\r\n"
"</body>\r\n"
"</html>\r\n"
};

/*const unsigned char Err404Side[] = {
"<html>\r\n"
"<head><title>404 Not Found</title></head>\r\n"
"<body>\r\n"
"Webseite nicht gefunden\r\n"
"</body>\r\n"
"</html>\r\n"
};*/

#endif		// #ifndef _WEBSIDE_INCLUDED_
